language: node_js
node_js:
- 10.5.0
env:
  global:
    secure: 2eab29e95ffb
before_install:
- pwd
- ll
- openssl aes-256-cbc -K $encrypted_2eab29e95ffb_key -iv $encrypted_2eab29e95ffb_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- cd webs
script:
- npm run build
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh travis@45.32.41.230 -o StrictHostKeyChecking=no