version: "3.1"

services:
  lamp:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/home/chwech/docker/passwd-manager/tp5:/app"
      - "/home/chwech/docker/passwd-manager/mysql-data:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - default
      - nginx_with_others

networks:
  nginx_with_others:
    external: true
