version: "3"

services:
  php7.2-apache:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - "/home/chwech/passwd-manager/tp5:/var/www/html"
    ports:
      - "8081:80"
      
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd-admin
      MYSQL_DATABASE: passwd-manager
