version: "3"

services:
  php7.2-apache:
    image: php:7.2-apache
    depends_on:
      - mysql
    volumes:
      - src:/home/chwech/passwd-manager/tp5

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd-admin

networks:

volumes:
  src: