version: "3"

services:
  apache:
    build:
      context: .
      dockerfile: ./httpd/Dockerfile
    volumes:
      - "/home/chwech/passwd-manager/tp5:/usr/local/apache2/htdocs/"
    ports:
      - "8081:80"
  
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd-admin
      MYSQL_DATABASE: passwd-manager
